import * as React from "react";
import type {GetStaticProps, NextPage} from "next";
import Head from "next/head";

import data from "../data.json";
import styles from "../styles/Home.module.scss";
import {Note} from "../types";

interface Props {
  notes: Note[];
}

const Home: NextPage<Props> = ({notes}) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta content="Generated by create next app" name="description" />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Los apuntes de Majo</h1>

        <p className={styles.description}>
          Majo here! 👋🏻, realizo apuntes a mano sobre las tecnologías más utilizadas.
        </p>

        <div className={styles.grid}>
          {notes.map((note) => (
            <a key={note.id} className={styles.card} href={`/${note.id}`}>
              <h2>{note.title} &rarr;</h2>
              <p>{note.description}</p>
            </a>
          ))}
        </div>
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      notes: data,
    },
    revalidate: 10,
  };
};

export default Home;
